config/routes.rb
Rails.application.routes.draw do
  
  get 'jobs_matrix/index'
  get 'jobs_matrix/jdp'
  get 'jobs_matrix/aggregator'

  get 'jdp/index'

  root 'home#index'

  get 'account' => 'account#index'
  get 'apply' => 'apply#index'
  get 'jobs_matrix' => 'jobs_matrix#index'

  get 'jobs' => 'jobs#index'
  get 'jobs/job_collapse' => 'jobs#job_collapse'
  get 'jobs/jdp' => 'jobs#jdp'
  get 'jobs/job_emailed_jdp' => 'jobs#job_emailed_jdp'
  get 'jobs/job_saved_jdp' => 'jobs#job_saved_jdp'
  get 'jobs/expired_job' => 'jobs#expired_job'
  get 'jobs/mobile_filters' => 'jobs#mobile_filters'
  get 'jobs/companyprofile' => 'jobs#companyprofile'
  get 'jobs/find_jobs_landing' => 'jobs#find_jobs_landing'
  get 'jobs/find_jobs_searchstate' => 'jobs#find_jobs_searchstate'
  get 'jobs/find_jobs_jobtitles' => 'jobs#find_jobs_jobtitles'
  get 'jobs/find_jobs_company' => 'jobs#find_jobs_company'
  get 'jobs/find_jobs_category' => 'jobs#find_jobs_category'
  get 'jobs/find_jobs_accounting' => 'jobs#find_jobs_accounting'
  get 'jobs/find_jobs_accounting_state' => 'jobs#find_jobs_accounting_state'
  get 'jobs/find_jobs_accounting_alabama_city' => 'jobs#find_jobs_accounting_alabama_city'
  get 'jobs/find_jobs_alabama' => 'jobs#find_jobs_alabama'
  get 'recommendations' => 'recommendations#index'
  get 'recommendations/similarrecs' => 'recommendations#similarrecs'
  get 'recommendations/resumerecs' => 'recommendations#resumerecs'
  get 'recprefs' => 'recommendations#recprefs'
  get 'recprefs_addlocation' => 'recommendations#recprefs_addlocation'
  get 'recprefs_addskills' => 'recommendations#recprefs_addskills'
  get 'recprefs_addtitle' => 'recommendations#recprefs_addtitle'
  get 'resumes' => 'resumes#index'
  get 'resumes/post' => 'resumes#post'
  get 'resumes/preview' => 'resumes#resume_preview'
  get 'resumes/cover_letter' => 'resumes#cover_letter'
  get 'resumes/resume_selected' => 'resumes#resume_selected'
  get 'resumes/cover_letter_blank' => 'resumes#cover_letter_blank'
  get 'saved_jobs' => 'saved_jobs#index'
  get 'saved_searches' => 'saved_searches#index'
  get 'sink' => 'sink#index'
  get 'sign_in' => 'user#sign_in'
  get 'sign_up' => 'user#sign_up'
  get 'jobs/after_apply' => 'jobs#after_apply'
  get 'jobs/job_emailed' => 'jobs#job_emailed'
  get 'jobs/job_saved' => 'jobs#job_saved'
  get 'dashboard' => 'home#dashboard'
  
  get 'home-one' => 'home#experiment-1'
  get 'home-two' => 'home#experiment-2'
  get 'home-three' => 'home#experiment-3'
  get 'home-four' => 'home#experiment-4'

  get 'info' => 'info#index'

end

app/views/shared/_checkbox_field.html.erb
	<%= check_box_tag(checkbox_id) %>
	<%= label_tag(checkbox_id, checkbox_label) %>

app/views/shared/_debug_menu_close.html.erb
		</section>
  <a class="exit-off-canvas"></a>
  </div>
</div>

app/views/shared/_debug_menu_open.html.erb
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <nav class="tab-bar debug">
      <section class="left">
        <a class="left-off-canvas-toggle" href="#"><i class="fa fa-info"></i><span>Page Info</span></a>
      </section>
      <section class="middle tab-bar-section">
        <h1 class="title">GRRP Interaction Prototype</h1>
      </section>
    </nav>
    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
      	<li><label>Session</label></li>
      	<% if @session %>
	        <% @session.each do |key, id| %>
	        	<li><%= link_to key, id %></li>
	        <% end %>
        <% end %>
      	<li><label>Authentication</label></li>
        <% if @authentication %>
	        <% @authentication.each do |key, id| %>
	        	<li><%= link_to key, id %></li>
	        <% end %>
        <% end %>
        <li><label>Statuses</label></li>
        <% if @statuses %>
	        <% @statuses.each do |key, id| %>
	        	<li><%= link_to key, id %></li>
	        <% end %>
        <% end %>
      </ul>
    </aside>
    <section class="main-section">

app/views/shared/_footer.html.erb
   <footer class="gs-footer-content">

      <div class="gs-footer">
      	<%if @footer_help != "no_help" %>
        <div class="gs-footer-helpbar">
          Need Help? <a href="#">help center</a>
        </div>
        <% end %>
        <div class="gs-footer-links">
          <div class="gs-footer-center gs-footer-langage-picker-enable">
            <div class="gs-footer-links-bloc">
              <ul>
                <li>job seekers</li>
                <li><a href="#">Find Jobs</a></li>
                <li><a href="#">Top Categories</a></li>
                <li><a href="#">Top Locations</a></li>
                <li><a href="#">Top Keywords</a></li>
                <li><a href="#">Partner Job Boards</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Sitemap</a></li>
              </ul>
            </div>
            <div class="gs-footer-links-bloc">
              <ul>
                <li>employers</li>
                <li><a href="#">Search Resumes</a></li>
                <li><a href="#">Post Jobs</a></li>
                <li><a href="#">Talent Networks</a></li>
                <li><a href="#">Advertising</a></li>
                <li><a href="#">Our Partners</a></li>
              </ul>
            </div>
            <div class="gs-footer-links-bloc">
              <ul class="gs-footer-links-ul-align">
                <li>social</li>
                <li><a href="#"><span class="fa fa-twitter-square"></span></a></li>
                <li><a href="#"><span class="fa fa-facebook-square"></span></a></li>
                <li><a href="#"><span class="fa fa-linkedin-square"></span></a></li>
              </ul>
              <ul>
                <li>legal</li>
                <li><a href="#">Security &amp; Fraud</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Terms</a></li>
                <li class="gs-footer-partner"><a class="logo-ad-choices" href="#" >Ad Choices</a></li>
              </ul>
            </div>
            <div class="gs-footer-links-bloc">
              <ul>
                <li>careerbuilder</li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Work at CareerBuilder</a></li>
              </ul>
              <ul class="gs-footer-links-ul-nolink">
                <li>200 N. LaSalle St.</li>
                <li>Suite 1100</li>
                <li>Chicago, IL 60601</li>
              </ul>
            </div>
            <div class="gs-footer-mobile-menu-user">
              <a href="#">Sign In</a>
      <!--          <a href="#">FirstName</a><a href="#">Sign Out</a>-->
            </div>
            <div class="gs-footer-links-bloc gs-footer-langage-picker">
              <ul>
                <li>language</li>
                <li>

                  <a id="gs-language-picker" href="www.google.com">English <span class="fa fa-angle-down"></span></a>
                  <ul id="gs-language-picker-submenu">
                    <li><a href="">French</a></li>
                    <li><a href="">Spanish</a></li>
                    <li><a href="">Portugese</a></li>
                  </ul>

                </li>
              </ul>
            </div>
            <div class="gs-footer-mobile-apps">
              <a href="#"><img src="http://img.icbdr.com/images/headerfooter/logo-app_store.png" width="100"></a><a href="#"><img src="http://img.icbdr.com/images/headerfooter/logo-google_play.png" width="100"></a>
            </div>
            <div class="gs-footer-mobile-links">
              <a href="#">Terms</a><a href="#">Privacy</a><a href="#">Full Site</a>
            </div>
        </div>
      </div>
      <div class="gs-footer-legal">
        &#169; CareerBuilder LLC, ALL right reserved
      </div>
    </footer>

app/views/shared/_footer_old.html.erb
  <footer class=<%= @footer_bar %>>
    	<div class="help-center">
	    	<div class="row help-center">
	    		<div class="column small-12 text-center">
	    			<h5>Help Center</h5>
	    		</div>
	    	</div>
	    </div>
    	<div class="row">
    		<div class="column small-12">
    			<ul class="large-block-grid-5">
    				<li>
    					<b>Job Seeker</b>
    					<ul class="no-bullet">
    						<li>Find Jobs
								<li>Top Categories</li>
								<li>Top locations</li>
								<li>Top-Term</li>
								<li>Partner Network</li>
								<li>Career Advice</li>
								<li>Site</li>
							</ul>
						</li>
						<li>
    					<b>Employer</b>
    					<ul class="no-bullet">
								<li>Search Resumes</li>
								<li>Jobs Items</li>
								<li>Talent Networks</li>
								<li>Advertising</li>
								<li>Our Network</li>
							</ul>
						</li>
						<li>
    					<b>Social</b>
    					<ul class="no-bullet">
								<li>Facebook</li>
								<li>Google</li>
							</ul>
							<br>
							<b>Legal</b>
    					<ul class="no-bullet">
								<li>Fraud</li>
								<li>Privacy Policy</li>
							</ul>
						</li>
						<li>
    					<b>Careerbuilder</b>
    					<ul class="no-bullet">
    						<li>About Us</li>
								<li>Work at CareerBuilder</li>
								<li><br></li>
								<li>200 N. LaSalle St</li>
								<li>Suite 1100</li>
								<li>Chicago, IL 60601</li>
							</ul>
						</li>
						<li>
    					<b>Language</b>
    					<select>
    						<option value="english">English</option>
    						<option value="spanish">Spanish</option>
    					</select>
						</li>
					</ul>
				</div>
			</div>
		</footer>

app/views/shared/_global_alerts.html.erb
<% if params[:warning] == 'true' || params[:error] == 'true' || params[:message] == 'true' || params[:success] == 'true' %>
	<div data-magellan-expedition="fixed">
		<dl class="sub-nav">
			<dd>
				<% if params[:warning] == 'true' %>
					<div data-alert class="alert-box true warning">
						<div class="row">
							<div class="column small-12 medium-12 large-12">
								<%= @warning_message.html_safe %>
								<a href="#" class="close">&times;</a>
							</div>
						</div>
					</div>
				<% end %>
				<% if params[:error] == 'true' %>
					<div data-alert class="alert-box true alert">
						<div class="row">
							<div class="column small-12 medium-12 large-12">
								<%= @error_message.html_safe %>
							</div>
						</div>
					</div>
				<% end %>
				<% if params[:message] == 'true' %>
					<div data-alert class="alert-box true">
						<div class="row">
							<div class="column small-12 medium-12 large-12">
								<%= @message_message.html_safe %>
							</div>
						</div>
					</div>
				<% end %>
				<% if params[:success] == 'true' %>
					<div data-alert class="alert-box success true">
						<div class="row">
							<div class="column small-11">
								<%= @success_message.html_safe %>
							</div>
						</div>
						<a href="#" class="close right">&times;</a>
					</div>
				<% end %>
			</dd>
		</dl>
	</div>
<% end %>

app/views/shared/_global_header.html.erb
<nav class='nav_bar <%= @nav_bar %>'>
	<div class="row">
		<div class="column small-12">
  		<div class="top-bar" data-topbar role="navigation">
			  <ul class="title-area">
			    <li class="name">
			      <h1><%= link_to "Careerbuilder", root_path %></h1>
			    </li>
			    <li class="toggle-topbar right">
			    	<a href="">
			    		<span><i class="fa fa-navicon"></i></span>
			    	</a>
			    </li>
			    <% if @search_bar != "no-search" %>
				    <li class="toggle-topbar-2 right">
				    	<a href="#" id="search-toggle-button" onclick="toggle_visibility('search-toggle-button','search-toggle');">
				    		<span><i class="fa fa-search"></i></span>
				    	</a>
				    </li>
				   <% end %>
				   <li class="toggle-topbar-2 right">
				    	<a data-dropdown="drop1" aria-controls="drop1" aria-expanded="false">
				    		<span class="fa-stack">
				    			<i class="fa fa-circle red fa-lg fa-stack-1x fa-stack-1-5x"></i>
				    			<strong class="fa-stack-1x fa-stack-text fa-inverse">1</strong>
				    			<!-- <i class="fa fa-bell fa-stack-1x"></i> -->
				    		</span>
				    	</a>
				    </li>
			  </ul>
			  <section class="top-bar-section">
			    <!-- Right Nav Section -->
			    <ul class="right">
			    	<% if @auth == "unknown" %>
			      	<li class=""><%= link_to "Sign In", sign_in_path %></li>
			      <% elsif @auth == "known" %>
			      	<li class=""><%= link_to "Sign In", sign_in_path %></li>
			      <% elsif @auth == "authenticated" %>
			      	<li class="has-dropdown hide-for-small-only">
			      		<%= link_to "Hi, Paul" %>
			      		<ul class="dropdown">
			      			<li><%= link_to "My Account", account_path %></li>
			      			<li><%= link_to "Sign Out", root_path(auth: "known", signed_out: true) %></li>
			      		</ul>
			      	</li>
			      	<li class="toggle-topbar-3 show-for-medium-up">
					    	<a data-dropdown="drop1" aria-controls="drop1" aria-expanded="false">
					    		<span class="fa-stack">
					    			<i class="fa fa-circle red fa-lg fa-stack-1x fa-stack-1-5x"></i>
					    			<strong class="fa-stack-1x fa-stack-text fa-inverse">1</strong>
					    			<!-- <i class="fa fa-bell fa-stack-1x"></i> -->
					    		</span>
					    	</a>
					    </li>
			      <% end %>
			      <li class="show-for-large-up"><a href="#">Employers</a></li>
			    </ul>

			    <!-- Left Nav Section -->
			    <ul class="left">
			      <li><%= link_to "Find Jobs", jobs_find_jobs_landing_path %></li>
			      <li><%= link_to "Recommendations", recommendations_path %></li>
			      <li><%= link_to "Resumes", resumes_path %></li>
			      <% if @auth == "authenticated" %>
			      	<li class="show-for-small-only"><%= link_to "My Account", account_path %></li>
			      	<li class="show-for-small-only"><%= link_to "Sign Out", root_path(auth: "known", signed_out: true) %></li>
			      <% end %>
			    </ul>
			  </section>
			</div>
		</div>
	</div>
</nav>
<section class="global-search <%= @search_bar %>" id="search-toggle">
  <div class="row">
  	<div class="column small-12 medium-9 medium-centered">
		  <%= form_tag(jobs_path, method: "get") do %> 
		  	<div class="row collapse no-bottom-padding">
			  	<div class="medium-4 small-12 columns">
			  		<label>Keyword
			  			<input type="text" name="keyword" placeholder="" />
						</label>
			  	</div>
			  	<div class="medium-4 small-12 columns">
			  		<label>Location
			  			<input type="text" name="location" placeholder="" />
						</label>
			  	</div>
			  	<div class="medium-4 small-12 columns end">
			  		<%= submit_tag "Search", class: "button postfix" %>
			  	</div>
			  <% end %>
			  <% if params[:controller] == "home" %>
			  	<%= render 'home/recent_searches' %>
				</div>
			<% end %>
		</div>
  </div>
</section>

<ul id="drop1" data-dropdown-content class="f-dropdown notifications" aria-hidden="true" tabindex="-1">
	<li class="new-notification">
		<a href="#">
			<h3 class="no-bottom-margin">Careerbuilder</h3>
			has viewed your resume
		</a>
	</li>
	<li>
		<a href="#">
			<h3 class="no-bottom-margin">Careerbuilder</h3>
			has viewed your resume
		</a>
	</li>
	<li>
		<a href="#">
			<h3 class="no-bottom-margin">Careerbuilder</h3>
			has viewed your resume
		</a>
	</li>
</ul>	

app/views/shared/_resume_privacy.html.erb
<div class="row">
	<div class="column small-10 medium-11">
		<h3>Make your resume Public?</h3>
		Yes, make my resume visible to employers searching resumes.</div>
	<div class="switch small round column small-2 medium-1 right">
		  <input id="exampleCheckboxSwitch" type="checkbox" checked>
		  <label for="exampleCheckboxSwitch"></label>
	</div> 
</div>

app/views/shared/_salary_job.html.erb
<div class="row">
	<div class="column small-12">
		<label>Salary</label>
		<div class="row">
			<div class="column small-5 medium-5">
				<input type="text" placeholder="" />
			</div>
			<div class="column small-2 medium-2 text-center">
				PER
			</div>
			<div class="column small-5 medium-5">
				<div class="row">
					<div class="column small-12">
						<select>
							<option value="husker">Hour</option>
							<option value="starbuck">Year</option>
						</select>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_time_start_end_fields.html.erb
<div class="row">
	<div class="column small-12">
		<label>Time Period</label>
		<div class="row">
			<div class="column small-5 medium-5">
				<div class="row">
					<div class="column small-6">
						<select>
							<option value="husker">Jan</option>
							<option value="starbuck">Feb</option>
							<option value="hotdog">March</option>
							<option value="apollo">April</option>
						</select>
					</div>
					<!-- End Month-->
					<div class="column small-6 medium-6">
						<input type="text" placeholder="Year" value="" />
					</div>
					<!-- End Year-->
				</div>
			</div>
			<div class="column small-2 medium-2 text-center">
				TO
			</div>
			<div class="column small-5 medium-5">
				<div class="row">
					<div class="column small-6">
						<select>
							<option value="husker">Jan</option>
							<option value="starbuck">Feb</option>
							<option value="hotdog">March</option>
							<option value="apollo">April</option>
						</select>
					</div>
					<!-- End Month-->
					<div class="column small-6 medium-6">
						<input type="text" placeholder="Year" value="" />
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="column small-12">
		<input id="checkbox2" type="checkbox"><label for="checkbox2">I currently work here</label>
	</div>
</div>