config/routes.rb
Rails.application.routes.draw do
  
  get 'jobs_matrix/index'
  get 'jobs_matrix/jdp'
  get 'jobs_matrix/aggregator'

  get 'jdp/index'

  root 'home#index'

  get 'account' => 'account#index'
  get 'apply' => 'apply#index'
  get 'jobs_matrix' => 'jobs_matrix#index'

  get 'jobs' => 'jobs#index'
  get 'jobs/job_collapse' => 'jobs#job_collapse'
  get 'jobs/jdp' => 'jobs#jdp'
  get 'jobs/job_emailed_jdp' => 'jobs#job_emailed_jdp'
  get 'jobs/job_saved_jdp' => 'jobs#job_saved_jdp'
  get 'jobs/expired_job' => 'jobs#expired_job'
  get 'jobs/mobile_filters' => 'jobs#mobile_filters'
  get 'jobs/companyprofile' => 'jobs#companyprofile'
  get 'jobs/find_jobs_landing' => 'jobs#find_jobs_landing'
  get 'jobs/find_jobs_searchstate' => 'jobs#find_jobs_searchstate'
  get 'jobs/find_jobs_jobtitles' => 'jobs#find_jobs_jobtitles'
  get 'jobs/find_jobs_company' => 'jobs#find_jobs_company'
  get 'jobs/find_jobs_category' => 'jobs#find_jobs_category'
  get 'jobs/find_jobs_accounting' => 'jobs#find_jobs_accounting'
  get 'jobs/find_jobs_accounting_state' => 'jobs#find_jobs_accounting_state'
  get 'jobs/find_jobs_accounting_alabama_city' => 'jobs#find_jobs_accounting_alabama_city'
  get 'jobs/find_jobs_alabama' => 'jobs#find_jobs_alabama'
  get 'recommendations' => 'recommendations#index'
  get 'recommendations/similarrecs' => 'recommendations#similarrecs'
  get 'recommendations/resumerecs' => 'recommendations#resumerecs'
  get 'recprefs' => 'recommendations#recprefs'
  get 'recprefs_addlocation' => 'recommendations#recprefs_addlocation'
  get 'recprefs_addskills' => 'recommendations#recprefs_addskills'
  get 'recprefs_addtitle' => 'recommendations#recprefs_addtitle'
  get 'resumes' => 'resumes#index'
  get 'resumes/post' => 'resumes#post'
  get 'resumes/preview' => 'resumes#resume_preview'
  get 'resumes/cover_letter' => 'resumes#cover_letter'
  get 'resumes/resume_selected' => 'resumes#resume_selected'
  get 'resumes/cover_letter_blank' => 'resumes#cover_letter_blank'
  get 'saved_jobs' => 'saved_jobs#index'
  get 'saved_searches' => 'saved_searches#index'
  get 'sink' => 'sink#index'
  get 'sign_in' => 'user#sign_in'
  get 'sign_up' => 'user#sign_up'
  get 'jobs/after_apply' => 'jobs#after_apply'
  get 'jobs/job_emailed' => 'jobs#job_emailed'
  get 'jobs/job_saved' => 'jobs#job_saved'
  get 'dashboard' => 'home#dashboard'
  
  get 'home-one' => 'home#experiment-1'
  get 'home-two' => 'home#experiment-2'
  get 'home-three' => 'home#experiment-3'
  get 'home-four' => 'home#experiment-4'

  get 'info' => 'info#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :debug, :statuses
	def index
		if session[:auth] == "authenticated" && params[:experiment] == "true"
			render 'dashboard_experiment'
		elsif session[:auth] == "authenticated"
			if params[:status] == "resume_deleted"
				session[:resumes] -= 1
			end
			if params[:status] == "cover_letter_deleted"
				session[:cover_letter] -= 1
			end
			render 'dashboard'
		else
			render 'index'
		end
	end

	private
	def statuses
		if params[:status] == "resume_deleted"
			@success_message = "Your resume has been deleted"
		end
		if params[:status] == "cover_letter_deleted"
			@success_message = "Your cover letter has been deleted"
		end
	end
  def debug
  	@statuses = {
  		"sign out" => {
  			:signed_out => "true"
  		}, 
  		"account deleted" => {
  			:deleted_account => "true"
  		}
  	}
  end
end

app/views/home/_recent_searches.html.erb
<% if session[:recent_searches].count > 0 %>
	<div class="row no-top-margin">
		<div class="column small-12 text-center no-bottom-padding">
			<h2>Your Recent Searches</h2>
		</div>
		<div class="column small-12 text-center">
			<div class="row no-bottom-padding no-top-padding">
				<div class="column">
					<% session[:recent_searches].each_with_index do |item, index| %>
						<ul class="inline-list recent no-bottom-margin">
							<li>
							</li>
							<li>
								<h3><%= link_to "#{item[0].capitalize}, #{item[1].capitalize}", jobs_path(keyword: item[0], location: item[1], recent: "true") %></h3>
							</li>
							<li>
								<h3><%= link_to "(100 new)", jobs_path(keyword: item[0], location: item[1], recent: "true", sort: "date"), class: "recent_new" %></h3>
							</li>
							<li>
							</li>
						</ul>
						<% if index == 0 && session[:auth] == "unknown" %>
						<div class="row text-left">
							<div class="panel column small-12 medium-7 medium-centered" >
								<div class="row">
									<div class="column small-12 text-center">
										<h3>Be the first to hear when <%= "#{item[0].capitalize}, #{item[1].capitalize}" %> are posted</h3>
									</div>
								</div>
								<div class="row collapse" id="bump">
									<div class="column small-12 medium-6 medium-offset-1">
										<%= render 'shared_molecules/form_fields/email_field', email_label: "Your Email" %>
									</div>
									<div class="column small-12 medium-4 end">
										<a class="button postfix" id="double-half-bump">Create Job Alert</a>
									</div>
								</div>
							</div>
						</div>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/home/dashboard.html.erb
<!-- TODO
	* Recent Searches
-->


<div class="row">
	<div class="column small-12">
		
	</div>
	<div class="column small-12 large-2">
		<h1>My Career</h1>
		<ul class="side-nav">
		  <li><a href="#recommendations">Recommendations</a></li>
		  <li><a href="#saved-jobs-apps">Saved Jobs</a></li>
		  <li><a href="#job-alerts">Job Alerts</a></li>
		  <li><a href="#resumes" class="hide-for-large--only">Resumes</a></li>
		  <li><a href="#cover-letters" class="hide-for-large--only">Cover Letters</a></li>
		  <!-- <li><%= link_to "Account Settings", account_path %></li> -->
		</ul>
	</div>

	<div class="column small-12 large-7">
		<!-- RECCOMMENDATIONS -->
		<h2 id="recommendations">50 Recommendations</h2>
		<% 10.times do |i| %>
			<%= render 'jobs/results/result_nosnapshot_noactions_nocollapse', count: i %>
		<% end %>
		<a class="button secondary expand">See All Recommendations</a>
		<!-- END RECCOMMENDATIONS -->
		
		<!-- SAVED JOBS -->
		<h2 id="saved-jobs-apps">30 Saved Jobs & Applications</h2>
		<div class="row">
			<% 5.times do %>
				<div class="column small-12">
					<h5>Interaction Designer</h5>
					<p>ABC Consulting Group | Atlanta, GA</p>
					<p><b>Expires 7/1/15</b></p>
					<hr />
	        <!--TODO add progress bar-->
	        <p>Progress Bar Placeholder</p>
	        <a href="#" class="button">Next Step: Apply</a>
	        <p>Add Notes</p>
	        <a href="../recommendations/similarrecs">See Similar Jobs</a>
	        <hr />
	    	</div>
			<% end %>
		</div>
		<a class="button secondary expand">See All Saved Jobs & Applications</a>
		<!-- END SAVED JOBS -->

		<!-- JOB ALERTS -->
		<h2 id="job-alerts">5 Job Alerts</h2>
		<div class="row">
			<% 5.times do %>
				<div class="small-12 columns">
					<h5>Interaction Designer Jobs in Atlanta, GA</h5>
					<p>Alert Frequency</p>
					<label for="dailyfrequency">
						<input type="radio" id="dailyfrequency">
						Daily
					</label>
					<label for="weeklyfrequency">
						<input type="radio" id="weeklyfrequency">
						Weekly
					</label>
	    	</div>
			<% end %>
		</div>
		<a class="button secondary expand">See All Job Alerts</a>
		<!-- END JOB ALERTS -->
	</div>

	<div class="column small-12 large-3">
		<!-- RESUMES -->
		<%= render 'home/molecules/resume_module' %>
		<!-- END RESUMES -->
		
		<!-- COVER LETTERS -->
		<%= render 'home/molecules/coverletter_module' %>
		<!-- END COVER LETTERS -->
	</div>
</div>

app/views/home/dashboard_experiment.html.erb
<% @search_bar = "no-search" %>
<div class="row">
	<div class="column small-12 large-3">
		<div class="row panel">
			<div class="column small-12 text-center">
				<span class="fa-stack fa-2x">
					<i class="fa fa-circle fa-stack-2x "></i>
					<i class="fa fa-user fa-stack-1x fa-inverse"></i>
				</span>
			</div>
			<div class="column small-12 text-center">
				<h2>Hi, Paul Person</h2>
			</div>
		</div>
		<div class="row">
			<%= render 'home/molecules/resume_module' %>
		</div>
		<div class="row">
			<%= render 'home/molecules/coverletter_module' %>
		</div>
	</div>
	<div class="column small-12 large-9">
		<div class="row">
			<div class="column small-12">
				<ul class="inline-list dashboard">
					<li>
						<div class="panel" style="padding: .875em 2em .5em">
							<ul class="inline-list" style="display:inline-block; text-align:left;">
								<li>
									<a><i style="line-height: 1.6125em; margin-left: auto; margin-right: auto;" class="fa fa-thumbs-o-up fa-lg"></i></a>
								</li>
								<li>
									<h1 style="line-height: .875em; margin-bottom: 0"><a>50</a></h1>
								</li>
								<li>
									<label style="line-height:2.25em"><a>job recommendations</a></label>
								</li>
							</ul>
						</div>
					</li>
					<li>
						<div class="panel" style="padding: .875em 2em .5em">
							<ul class="inline-list" style="display:inline-block; text-align:left;">
								<li>
									<a><i style="line-height: 1.6125em; margin-left: auto; margin-right: auto;" class="fa fa-eye fa-lg"></i></a>
								</li>
								<li>
									<h1 style="line-height: .875em; margin-bottom: 0"><a>37</a></h1>
								</li>
								<li>
									<label style="line-height:2.25em"><a>resume views</a></label>
								</li>
							</ul>
						</div>
					</li>
					<li>
						<div class="panel" style="padding: .875em 2em .5em">
							<ul class="inline-list" style="display:inline-block; text-align:left;">
								<li>
									<a><i style="line-height: 1.6125em; margin-left: auto; margin-right: auto;" class="fa fa-group fa-lg"></i></a>
								</li>
								<li>
									<h1 style="line-height: .875em; margin-bottom: 0"><a>&nbsp;4</a></h1>
								</li>
								<li>
									<label style="line-height:2.25em"><a>competition reports</a></label>
								</li>
							</ul>
						</div>
					</li>
					<li>
						<div class="panel" style="padding: .875em 2em .5em">
							<ul class="inline-list" style="display:inline-block; text-align:left;">
								<li>
									<a><i style="line-height: 1.6125em; margin-left: auto; margin-right: auto;" class="fa fa-bell fa-lg"></i></a>
								</li>
								<li>
									<h1 style="line-height: .875em; margin-bottom: 0"><a>&nbsp;2</a></h1>
								</li>
								<li>
									<label style="line-height:2.25em"><a>search alerts</a></label>
								</li>
							</ul>
						</div>
					</li>
					<li>
						<div class="panel" style="padding: .875em 2em .5em">
							<ul class="inline-list" style="display:inline-block; text-align:left;">
								<li>
									<a><i style="line-height: 1.6125em; margin-left: auto; margin-right: auto;" class="fa fa-group fa-lg"></i></a>
								</li>
								<li>
									<h1 style="line-height: .875em; margin-bottom: 0"><a>18</a></h1>
								</li>
								<li>
									<label style="line-height:2.25em"><a>industry articles</a></label>
								</li>
							</ul>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/home/experiment-4.html.erb
<script>
$(document).ready(function() {
	$('#fullpage').fullpage({
		verticalCentered: false
	});
});
</script>

<% @nav_bar = "no-nav" %>
<% @footer_help = "no_help" %>
<div class="home-exp-4">
	<div id="fullpage">
		<div class="section">
			<div class="hero" style="display:table; table-layout:fixed; height:100%; width:100%;">
				<div class="row logo" style="display:table-row;">
					<div class="column small-12">
						<h2 class="subheader left"><a style="margin-top: 0; line-height:inherit;" href="../home-two">careerbuilder</a></h2>
						<ul class="inline-list right" style="margin-bottom: 0; margin-top: .25em;">
							<li>
								<a class="button" href="<%= sign_in_path %>" style="margin-bottom: 0; line-height:2.5em; padding: 0 1.25em; height: inherit; background-color: #1B7CB2;">
									Sign In
								</a>
							</li>
							<li>
								<a href="#registration" style="margin-bottom: 0; line-height:2.5em;">
									Sign Up
								</a>
							</li>
							<li>
								<a href="http://www.careerbuilderforemployers.com/" style="margin-bottom: 0; line-height:2.5em;">
									Employers
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="display: table-row;">
					<div class="search" style="display: table; table-layout: fixed; width: 100%; height: 90%;">
						<div class="display:table-row">
							<div class="display:table-cell vertical-align:middle;">
								<div class="row" style="">
									<div class="column small-12 medium-10 medium-centered">
										<h1 style="line-height: 1.125; margin-left: 2.45em; margin-bottom: .75em; color: #fff" class="subheader">
										Find the Right Job.<strong> Right Now.</strong>
										</h1>
										<div class="row collapse">
											<div class="column small-4 small-push-1">
												<label>keyword
													<input type="text" id="search-key">
												</label>
											</div>
											<div class="column small-4 small-push-1">
												<label>location
													<input type="text" id="search-loc">
												</label>
											</div>
											<div class="column small-2 small-push-1 end">
												<a class="button expand postfix" id="search-btn">Search</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div style="display:table-row">
					<div class="downarrow" style="display: table-cell; vertical-align:bottom;">
						<a style="background: none;" onclick="$.fn.fullpage.moveSectionDown();"><i class="fa fa-angle-down fa-3x" style="color: #fff; display:block; text-align:center;"></i></a>
					</div>
				</div>
			</div>
		</div>

		<div class="section">
			<div class="registration" id="registration" style="display: table; table-layout:fixed; height:98%; width: 100%;">
				<div style="display:table-row">
					<div class="uparrow" style="display: table-cell; vertical-align:top;">
						<a style="background: none;" onclick="$.fn.fullpage.moveSectionUp();"><i class="fa fa-angle-up fa-3x" style="color: #1B7CB2; display:block; text-align:center;"></i></a>
					</div>
				</div>
				<div class="row" style="display: table-row; vertical-align:middle;">
					<div class="column small-12 medium-10 medium-centered">
						<div class="row">
							<div class="small-12 columns">
								<h2 class="text-center subheader" >
									Get started with an account.
								</h2>
								<p class="subheader text-center" style="margin-bottom:1em;">Upload a resume to get started.</p>
							</div>
							<div class="small-12 medium-6 medium-centered column">
								<%= form_tag(@path, method: "get", id: "demo-upload", class: "dropzone", style: "padding: 1.5em 0;", :data => {:equalizer_watch => {}}) do %>
									<div class="dz-message">
										<i class="fa fa-cloud-upload fa-4x" style="color:#1B7CB2"></i>
										<h2 style="margin-bottom:0;">DRAG &amp; DROP</h2>
										<h2 class="subheader" style="line-height:0.75em;">
											or
										</h2>
										<h3 class="subheader">
											click to browse
										</h3>
										<h3>
											<small>
												We accept .DOCX, .DOC, .RTF, .TXT, .PDF up to 1 MB.
											</small>
										</h3>
										<div class="fallback">
											<input type="file" name="file" />
										</div>
									</div>
								<% end %>
							</div>
							<div class="small-12 columns" style="margin-top: 2em;">
								<h3 class="text-center" style="margin-bottom: 1em;">
									Why create an account?
								</h3>
								<div class="small-12 medium-10 medium-push-1 columns double-bump">
									<ul class="large-block-grid-4 medium-block-grid-4">
										<li>
											<div class="small-12">
												<i class="fa fa-search fa-3x" style="color:#444"></i>
												<br>
											</div>
											<div class="small-12 text-center bump">
												Know when a company <br/>finds your resume.
											</div>
										</li>
										<li>
											<div class="small-12">
												<i class="fa fa-file-text fa-3x" style="color:#444"></i>
												<br>
											</div>
											<div class="small-12 text-center bump">
												Save up to 5 resumes to <br/>quickly apply to jobs.
											</div>
										</li>
										<li>
											<div class="small-12">
												<i class="fa fa-bell fa-3x" style="color:#444"></i>
												<br>
											</div>
											<div class="small-12 text-center bump">
												Be notified when your <br/>application is viewed.
											</div>
										</li>
										<li>
											<div class="small-12">
												<i class="fa fa-group fa-3x" style="color:#444"></i>
												<br>
											</div>
											<div class="small-12 text-center bump">
												View the competition <br/>when applying to jobs.
											</div>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<!-- REGISTRATION TO GO HERE -->
				</div>
				<div style="display:table-row">
					<div class="downarrow" style="display: table-cell; vertical-align:top;">
						<a style="background: none;" onclick="$.fn.fullpage.moveSectionDown();"><i class="fa fa-angle-down fa-3x" style="color: #1B7CB2; display:block; text-align:center;"></i></a>
					</div>
				</div>
			</div>
		</div>
		<div class="section">
			<div id="scroll">
				<div class="sob-story" style="background-color: #f5f5f5; padding: .5em 0 0;">
					<div class="row">
						<div class="column small-12 medium-5 medium-offset-2" style="padding-top: 1.75em;">
							<h2 class="subheader">Stay <strong>Connected</strong></h2>
							<p class="subheader">Quickly find job opportunities wherever you want with location-based search. Get automatic recommendations and notifications based on your job searches. Apply to jobs with your Careerbuilder resumes with just a couple taps.</p>
							<a class="button" style="background-color:#000; padding: .3125em 1.5em 0em; border-radius: 8px; height: inherit;">
								<ul class="inline-list">
									<li>
										<i class="fa fa-mobile-phone fa-3x" style="margin-top: -0px; margin-bottom: -2px;"></i>
									</li>
									<li style="padding-top: .6875em;">
										<small style="line-height: .75;">Available on the<br></small>App Store
									</li>
								</ul>
							</a>

							<a class="button" style="background-color:#000; padding: .6125em 1.5em 0em; border-radius: 8px; height: inherit;">
								<ul class="inline-list" style="margin-top:2px; padding-bottom: 1px;">
									<li>
										<i class="fa fa-google fa-3x" style="padding-top: 6px; font-size: 32px;"></i>
									</li>
									<li class="text-left" style="padding-top: .5em;">
										<small style="line-height: .75;">GET IT ON<br></small>Google Play
									</li>
								</ul>
							</a>
						</div>
						<div class="column small-12 medium-3 end">
							<%= image_tag "experiment/app.png" %>
						</div>
					</div>
				</div>
				<div class="pop-searches" style="background-color: #fff; padding: 1em 0">
					<div class="row">
						<div class="column small-8 small-push-2 text-center">
							<h2 class="subheader"><strong>Popular</strong> Searches</h2>
						</div>
					</div>
					<div class="row">
						<div class="column small-8 small-push-2 end">
							<ul class="small-block-grid-5">
								<li><img src="http://placehold.it/150x150&text=Macys-Logo"></li>
								<li><img src="http://placehold.it/150x150&text=Macys-Logo"></li>
								<li><img src="http://placehold.it/150x150&text=Macys-Logo"></li>
								<li><img src="http://placehold.it/150x150&text=Macys-Logo"></li>
								<li><img src="http://placehold.it/150x150&text=Macys-Logo"></li>
							</ul>
							<div class="text-center">
								<a>Browse All Companies</a>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="column small-8 small-push-2 end">
							<br>
							<ul class="small-block-grid-5">
								<li><img src="http://placehold.it/150x150&text=Atlanta"></li>
								<li><img src="http://placehold.it/150x150&text=Atlanta"></li>
								<li><img src="http://placehold.it/150x150&text=Atlanta"></li>
								<li><img src="http://placehold.it/150x150&text=Atlanta"></li>
								<li><img src="http://placehold.it/150x150&text=Atlanta"></li>
							</ul>
							<div class="text-center">
								<a>Browse All Cities</a>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="small-8 small-push-2 end columns text-center">
							<br>
							<a href='<%= jobs_path(keyword: "sales") %>'>Sales</a>
							&nbsp;|&nbsp;
							<a href='<%= jobs_path(keyword: "customer service") %>'>Costumer Service</a>
							&nbsp;|&nbsp;
							<a href='<%= jobs_path(keyword: "accounting") %>'>Accounting</a>
							&nbsp;|&nbsp;
							<a href='<%= jobs_path(keyword: "entry level") %>'>Entry Level</a>
							&nbsp;|&nbsp;
							<a href='<%= jobs_path(keyword: "administrative assistant") %>'>Administrative Assistant</a>
							&nbsp;|&nbsp;
							<a href='<%= jobs_path(keyword: "registered nurse") %>'>Registered Nurse</a>
						</div>
						<div class="small-8 small-push-2 end columns text-center">
							<br>
							<a href='<%= jobs_find_jobs_category_path %>'> Browse All Catagories</a>
						</div>
					</div>
				</div>



				<!-- <div class="pop-searches" style="background-color: #fff; padding: 1em 0">
					<div class="row">
						<div class="column small-12 text-center">
							<h2 class="subheader" style="margin-bottom: 36px;">
								Don't know where to start? <strong>Check out Popular Searches.</strong>
							</h2>
						</div>
						<div class="column small-12 medium-8 medium-centered">
							<ul class="medium-block-grid-3">
								<li>
									<select>
										<option>Top Job Categories</option>
										<option>Sales</option>
										<option>Costumer Service</option>
										<option>Accounting</option>
										<option>Entry Level</option>
										<option>Administrative Assistant</option>
										<option>Retail</option>
										<option>Registered Nurse</option>
										<option>Browse All Categories</option>
									</select>
								</li>
								<li>
									<select>
										<option>Top Cities</option>
										<option>Chicago</option>
										<option>Atlanta</option>
										<option>Houston</option>
										<option>Dallas</option>
										<option>Boston</option>
										<option>New York</option>
										<option>San Francisco</option>
										<option>Miami</option>
										<option>Denver</option>
										<option>Browse All Cities</option>
									</select>
								</li>
								<li>
									<select>
										<option>Top Companies</option>
										<option>Macy's</option>
										<option>Robert Half</option>
										<option>UPS</option>
										<option>Aerotek</option>
										<option>Army National Guard</option>
										<option>UnitedHealth Group</option>
										<option>Kelly Services</option>
										<option>Browse All Companies</option>
									</select>
								</li>
							</ul>
						</div>
					</div>
				</div> -->
				<%= render 'shared/footer' %>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<% @search_bar = "no-search" %>
<div class="new-homepage">
	<div class="hero-wrapper">
		<div class="hero">
			<div class="row">
				<div class="column small-12 text-center">
					<h1>Find the Right Job. <strong>Right Now</strong></h1>
				</div>
			</div>
			<div class="row">
				<div class="column small-10 small-centered search">
					<div class="row collapse">
						<form>
							<div class="column input-wrapper">
								<label>KEYWORD
									<input type="text" id="search-key">
								</label>
							</div>
							<div class="column input-wrapper">
								<label>LOCATION
									<input type="text" id="search-loc">
								</label>
							</div>
							<div class="column input-wrapper">
								<input type="submit" class="button expand" value="FIND JOBS">
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="popular-search">
		<div class="row">
			<div class="column small-10 small-centered text-left">
				<h1>Popular <strong>job searches</strong></h1>
				<div class="row">
					<div class="column small-4">
						<h2>By Category</h2>
						<p>
							<a>Sales</a> • <a>Consumer Service</a> • <a>Accounting</a> • <a>Entry Level</a> • <a>Administrative Assistant</a> • <a>Retail</a> • <a>Registered Nurse</a>
						</p>
						<a class="browse"><%= image_tag 'popular-catagories.png'%><strong>Browse All Categories</strong></a>
					</div>
					<div class="column small-4">
						<h2>By City</h2>
						<p>
							<a>Chicago</a> • <a>Houston</a> • <a>Dallas</a> • <a>Boston</a> • <a>New York</a> • <a>Atlanta</a> • <a>San Francisco</a> • <a>Miami</a> • <a>Denver</a>
						</p>
						<a class="browse"><%= image_tag 'popular-cities.png'%><strong>Browse All Cities</strong></a>
					</div>
					<div class="column small-4">
						<h2>By Company</h2>
						<p>
							<a>Macy’s</a> • <a>Robert Half</a> • <a>UPS</a> • <a>Aerotek</a> • <a>Army National Guard</a> • <a>UnitedHealth Group<a> • <a>Kelly Service</a>
						</p>
						<a class="browse"><%= image_tag 'popular-companies.png'%><strong>Browse All Companies</strong></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>