config/routes.rb
Rails.application.routes.draw do
  
  get 'jobs_matrix/index'
  get 'jobs_matrix/jdp'
  get 'jobs_matrix/aggregator'

  get 'jdp/index'

  root 'home#index'

  get 'account' => 'account#index'
  get 'apply' => 'apply#index'
  get 'jobs_matrix' => 'jobs_matrix#index'

  get 'jobs' => 'jobs#index'
  get 'jobs/job_collapse' => 'jobs#job_collapse'
  get 'jobs/jdp' => 'jobs#jdp'
  get 'jobs/job_emailed_jdp' => 'jobs#job_emailed_jdp'
  get 'jobs/job_saved_jdp' => 'jobs#job_saved_jdp'
  get 'jobs/expired_job' => 'jobs#expired_job'
  get 'jobs/mobile_filters' => 'jobs#mobile_filters'
  get 'jobs/companyprofile' => 'jobs#companyprofile'
  get 'jobs/find_jobs_landing' => 'jobs#find_jobs_landing'
  get 'jobs/find_jobs_searchstate' => 'jobs#find_jobs_searchstate'
  get 'jobs/find_jobs_jobtitles' => 'jobs#find_jobs_jobtitles'
  get 'jobs/find_jobs_company' => 'jobs#find_jobs_company'
  get 'jobs/find_jobs_category' => 'jobs#find_jobs_category'
  get 'jobs/find_jobs_accounting' => 'jobs#find_jobs_accounting'
  get 'jobs/find_jobs_accounting_state' => 'jobs#find_jobs_accounting_state'
  get 'jobs/find_jobs_accounting_alabama_city' => 'jobs#find_jobs_accounting_alabama_city'
  get 'jobs/find_jobs_alabama' => 'jobs#find_jobs_alabama'
  get 'recommendations' => 'recommendations#index'
  get 'recommendations/similarrecs' => 'recommendations#similarrecs'
  get 'recommendations/resumerecs' => 'recommendations#resumerecs'
  get 'recprefs' => 'recommendations#recprefs'
  get 'recprefs_addlocation' => 'recommendations#recprefs_addlocation'
  get 'recprefs_addskills' => 'recommendations#recprefs_addskills'
  get 'recprefs_addtitle' => 'recommendations#recprefs_addtitle'
  get 'resumes' => 'resumes#index'
  get 'resumes/post' => 'resumes#post'
  get 'resumes/preview' => 'resumes#resume_preview'
  get 'resumes/cover_letter' => 'resumes#cover_letter'
  get 'resumes/resume_selected' => 'resumes#resume_selected'
  get 'resumes/cover_letter_blank' => 'resumes#cover_letter_blank'
  get 'saved_jobs' => 'saved_jobs#index'
  get 'saved_searches' => 'saved_searches#index'
  get 'sink' => 'sink#index'
  get 'sign_in' => 'user#sign_in'
  get 'sign_up' => 'user#sign_up'
  get 'jobs/after_apply' => 'jobs#after_apply'
  get 'jobs/job_emailed' => 'jobs#job_emailed'
  get 'jobs/job_saved' => 'jobs#job_saved'
  get 'dashboard' => 'home#dashboard'
  
  get 'home-one' => 'home#experiment-1'
  get 'home-two' => 'home#experiment-2'
  get 'home-three' => 'home#experiment-3'
  get 'home-four' => 'home#experiment-4'

  get 'info' => 'info#index'

end

app/controllers/jobs_matrix_controller.rb
class JobsMatrixController < ApplicationController
  def index
  end  

  def aggregator
  end

  def jdp

  if params[:branding] == 'premium'
			@premium_component = "show-me"
		elsif params[:branding] == "standard"
			@standard_component = "show-me"		
		elsif params[:branding] == "basic"
			@basic_component = "show-me"
		elsif params[:branding] == "unbranded" || params[:branding] == nil
			@unbranded_component = "show-me"
		end
  end
end

app/helpers/jobs_matrix_helper.rb
module JobsMatrixHelper
end

app/views/jobs_matrix/_degree_required_filter.html.erb
<label>Degree Required
	<select>
		<option>None (2,345)</option>
		<option>High School (456)</option>
		<option>2 Year Degree (789)</option>
		<option>4 Year Degree (345)</option>
		<option>Graduate Degree (98)</option>
	</select>
</label>

app/views/jobs_matrix/_jdp_ad.html.erb
<div class="row">

<div class="small-6 large-centered columns">
sdsdsfsdf
<div class="hide-for-small-only">
<img src="http://placehold.it/728x90&text=Ad+728+x+90" alt="premium banner">
</div>

</div>

</div>

app/views/jobs_matrix/_job_header.html.erb
<div id="scroll-spy-bar" class="row">

  <% if params[:branding] == "premium" || params[:branding] == "standard" || params[:branding] == "basic" %>

	<div  class="columns medium-4 large-3 hide-for-small-only scrollspy-premium-logo">
		<img src="http://placehold.it/180x180">
	</div><!--close column-->
	<div class="columns small-12 medium-8 large-9 columns scrollspy-premium-container">

<% else %>

	<div class="small-12 medium-12 large-12 columns ">

<% end %>
    <h1>Account Manager</h1>
    <p>1 Hour Ago</p>
    <p class="scrollspy-noshow">ABC Company</p>
    <p class="scrollspy-noshow">GA-Atlanta</p>
    <p class="scrollspy-button-toggle">  <%= link_to "Apply Now", apply_path, class: "button" %>
   </p>

  <div class="row scrollspy-noshow">
    <div class="small-12 medium-8 large-4 columns">
      <ul class="button-group">
          <li class="scrollspy-noshow"><a class="small button secondary email-drawer-link-jdp">Email Job</a></li>
          <% if @auth == "authenticated" %>
            <% if params[:action] != "job_saved_jdp" %>
            <li><a href="job_saved_jdp" class="small button secondary" id="job_saved_btn">Save Job</a></li>
            <% elsif %>
            <a id="job_saved_btn">Job Saved</a></li>
            <% end %>
          <% end %>
      </ul>
      <div class="hidden email-drawer-jdp">
          <div class="small-12 medium-12 large-12 columns">
            <% if session[:auth] == "authenticated" %>
            <label>From (Your Email Address)
            <input type="text" placeholder="prepopulatedemail@gmail.com" />
            </label>
            <% else %>
            <label>From (Your Email Address)
            <input type="text" placeholder="" />
            </label>
            <% end %>
            <label>To (Recipients Email Address)
            <input type="text" placeholder="" />
            </label>
            <label>Your Name
            <input type="text" placeholder="" />
            </label>
            <label>Notes
            <textarea placeholder=""></textarea>
            </label>
            <p>140 Characters Left</p>
            <a href="job_emailed_jdp" class="button small closedrawerjdp">Send Email</a>
            <a href="#" class="button secondary small closedrawerjdp">Cancel</a>
          </div>
      </div>
    </div>

    <div class="small-12 medium-4 large-2 large-offset-4 right columns">
      <%= link_to "Apply Now", apply_path, class: "button expand" %>
    </div><!--close column-->
  </div>
</div>
</div><!--close row-->

app/views/jobs_matrix/_job_result_2.html.erb
<% if params[:action] == "after_apply" %>
<% job_columns = "columns small-10 large-4" %>
<% company_columns = "small-10 large-2 columns" %>
<% location_columns = "small-10 large-2 columns" %>
<% date_columns = "small-10 large-2 columns" %>
<% elsif params[:action] == "resumerecs" %>
<% job_columns = "columns small-10 medium-5 large-5" %>
<% company_columns = "small-10 medium-2 large-2 columns" %>
<% location_columns = "small-10 medium-2 large-2 columns" %>
<% date_columns = "small-10 medium-1 large-1 columns" %>
<% else %>
<% job_columns = "columns small-12 medium-6 large-6" %>
<% company_columns = "small-12 medium-2 large-2 columns" %>
<% location_columns = "small-12 medium-2 large-2 columns" %>
<% date_columns = "small-12 medium-2 large-2 columns" %>
<% end %>
<!-- QUICK APPLY FOR AFTER APPLY -->
<!--QUICK APPLY FOR RESUME RECS -->
<div class="flip">
	<div class="card">
		<div class="front face">
			<div class='<%= job_columns %>' >
				<h2><%= link_to "Commercial Property and Casualty Insurance Account Executive", jobs_jdp_path %></h2>
				<p class="hide-for-small-only">Full-Time | Entry Level | $10/hr | Our client, a leader in the production of medical technology solutions has an immediate need for...</p>
				<ul class="inline-list show-for-large-up">
					<li><a class="emailJob">Email Job</a></li>
				</ul>
			</div>
			<div class='<%= company_columns %>'>
				<a href="jobs/companyprofile">Account Control Technology Inc.</a>
				</div><!--close column-->
				<div class='<%= location_columns %>'>
					<p>GA-Atlanta
					</p>
				</div>
				<div class='<%= date_columns %>'>
					<p>1 Hour Ago</p>
				</div>
				<hr />
			</div>
			<div class="face back">
				<div class="row">
					<div class="medium-12 columns">
						<% if session[:auth] == "authenticated" %>
						<h4>Email This Job</h4>
						<label>From (Your Email Address)
							<input type="text" placeholder="prepopulatedemail@gmail.com" />
						</label>
						<% else %>
						<label>From (Your Email Address)
							<input type="text" placeholder="" />
						</label>
						<% end %>
						<label>To (Recipients Email Address)
							<input type="text" placeholder="" />
						</label>
						<% if session[:auth] == "authenticated" %>
						<label>Your Name
							<input type="text" placeholder="Prepopulated Name" />
						</label>
						<% else %>
						<label>Your Name
							<input type="text" placeholder="" />
						</label>
						<% end %>
						<label>Notes
							<textarea placeholder=""></textarea>
						</label>
						<p>140 Characters Left</p>
						<%= link_to "Send Email", url_for(status: "email_sent", success: "true"), class: "button expand" %>
						<a class="button secondary expand">Cancel</a>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/jobs_matrix/_nextjob.html.erb
<div class="row">

     <div class="small-12 medium-3 large-3 columns hide-for-small-only vertical-bump">
        <a href="../jobs"> < Back to Search </a>
    </div><!--close columns-->

    <div class=" large-3 columns show-for-large-up">
        <p class="right vertical-bump" id="counter"><span id="current">1</span> of <span id="total">1456</span> Jobs in your search</p>
    </div><!--close columns-->

    <div class="medium-9 large-6 columns show-for-medium-up">
        <a class="button secondary right" id="count-up"> <i class="fa fa-chevron-right"></i> </a>
        <span class="next-job right button secondary">Next Job: <br />Entry-Level Sales/Management Training</span>
        <a href="" class="button secondary right" id="count-down"> <i class="fa fa-chevron-left"></i> </a>
    </div><!--close columns-->

    <div class="show-for-small-only">
        <div class="small-6 columns">
        <a href="" class="button secondary expand right" > <i class="fa fa-chevron-left"></i> Previous Job</a>
        </div>
        <div class="small-6 columns">
        <a class="button secondary expand right" > Next Job <i class="fa fa-chevron-right"></i> </a>
        </div>
    </div><!--close columns-->

</div><!--close row-->

app/views/jobs_matrix/aggregator.html.erb
<section class="central-container">
	<div class="row">
		<div class="columns large-12">
			<div class="panel email-container">
				
				<div class="row">
					<div class="columns medium-4">
						<h1>Account Manager</h1>
						<p class="jdp-detials">ABC Company <span class="fa fa-circle"></span> GA-Atlanta <span class="fa fa-circle"></span> 1 Hour Ago </p>
						<div class="btn-group">
				      <button class="btn btn-default" type="button">Save Job</button>
				      <button id="email-job" class="btn btn-default" type="button">Email</button>
				      <button class="btn btn-default" type="button">Report</button>
				    </div>
					</div>
					<div class="columns medium-6 ">
						<br/>
						<span class="right">
							<%= link_to "Avg. Salaries", apply_path, class: "btn" %>
							<%= link_to "Apply Now", apply_path, class: "btn" %>	
						</span>	
						<span>See how this job compares to other salaries nationwide:</span>

					</div>
				</div>
				<div class="row email-drawer-jdp" >
          <div class="small-12 medium-12 columns" style="margin: 0 0 0 btn35%;">
            <% if session[:auth] == "authenticated" %>
            <label>From (Your Email Address)
            <input type="text" placeholder="prepopulatedemail@gmail.com" />
            </label>
            <% else %>
            <label>From (Your Email Address)
            <input type="text" placeholder="" />
            </label>
            <% end %>
            <label>To (Recipients Email Address)
            <input type="text" placeholder="" />
            </label>
            <label>Your Name
            <input type="text" placeholder="" />
            </label>
            <label>Notes
            <textarea placeholder=""></textarea>
            </label>
            <p>140 Characters Left</p>
            <a href="job_emailed_jdp" class="button small closedrawerjdp">Send Email</a>
            <a href="#" class="button secondary small closedrawerjdp">Cancel</a>
          </div>
      	</div>
			</div>
		</div>
	</div>


	<!--main content-->
	<div class="row">
		<div class="columns large-8">
		  <div class="gs-panel">
				<div class="gs-panel-body">
					<h3> Job Description </h3>
					<h3 class='brand-specific <%= @premium_component %>'> premium </h3>
					<h3 class='brand-specific <%= @standard_component %>'> standard </h3>
					<h3 class='brand-specific <%= @unbranded_component %>'> unbranded</h3>
			    <p>SALES REPS NEEDED - B2B - OUTSIDE SALES - BUSINESS DEVELOPMENT MANAGERS 
			        <br /><br />
			        We are currently looking for outside sales representatives and account executives who have a background in outside sales, B2B, and business development.  If you are in sales and are confident in your sales abilities, then this opportunity may be for you.  We are looking for energetic sales reps and account executives with 5+ years of B2B outside sales and business development experience who would like an opportunity as an Outside Sales Rep with our company.
			        <br /><br />
			        SMS is the largest full-service business development firm serving small to mid-sized businesses in the US. Through the coordinated efforts of our corporate headquarters and field service personnel; SMS installs proven methods, systems, controls and incentives to enable business owners and their managers to maintain positive cash flow, control costs, and accelerate the growth of their companies.
			        SMS is currently seeking passionate, positive, driven outside sales professionals to sell into small & medium size company business owners, presidents and CEO’s.  As an outside sales rep, you will be working as a business development manager selling B2B.  You will hold a pivotal role in helping people achieve their dreams.    
			        <br /><br />
			        SALES REPS - B2B - OUTSIDE SALES - BUSINESS DEVELOPMENT MANAGERS
			        <br /><br />
			    </p>
			    <hr/>
				  <p class="more_jdp">
				  	<%= link_to jobs_matrix_jdp_path(branding:"premium")  do %>
						   View Full Job Description <span class="right fa fa-chevron-right"></span>
						<% end %>
				  </p>
			</div>
		  </div>
		  <h3>OTHER JOBS YOU MAY LIKE</h3>
		   <div class="gs-panel">
				<div class="gs-panel-body">
					
					<div class="row">
				  <div class='columns large-6 medium-6 small-10 ' >
				    <h2><%= link_to "Commercial Property and Casualty Insurance Account Executive - PREMIUM", jobs_jdp_path(branding:"premium") %></h2>
				  </div>
				  <div class='columns large-2 medium-2 small-2 right'>
				    <p class="right">1 Hour Ago</p>
				  </div>
				  <div class='columns large-2 medium-2'>
				    <a href="jobs/companyprofile">Account Control Technology Inc.</a>
				  </div><!--close column-->
				  <div class='columns large-2 medium-2'>
				    <p>Atlanta, Georgia</p>
				  </div>

				  <div class="columns large-12 hide-for-small-only">
				    <p class="">Full-Time | Entry Level | $10/hr | Our client, a leader in the production of medical technology solutions has an immediate need for...</p>
				  </div>


				</div>
				<hr/>
					<div class="row">
				  <div class='columns large-6 medium-6 small-10 ' >
				    <h2><%= link_to "Commercial Property and Casualty Insurance Account Executive - PREMIUM", jobs_jdp_path(branding:"premium") %></h2>
				  </div>
				  <div class='columns large-2 medium-2 small-2 right'>
				    <p class="right">1 Hour Ago</p>
				  </div>
				  <div class='columns large-2 medium-2'>
				    <a href="jobs/companyprofile">Account Control Technology Inc.</a>
				  </div><!--close column-->
				  <div class='columns large-2 medium-2'>
				    <p>Atlanta, Georgia</p>
				  </div>

				  <div class="columns large-12 hide-for-small-only">
				    <p class="">Full-Time | Entry Level | $10/hr | Our client, a leader in the production of medical technology solutions has an immediate need for...</p>
				  </div>

				  
				</div>
				<hr/>
				<div class="row">
				  <div class='columns large-6 medium-6 small-10 ' >
				    <h2><%= link_to "Commercial Property and Casualty Insurance Account Executive - PREMIUM", jobs_jdp_path(branding:"premium") %></h2>
				  </div>
				  <div class='columns large-2 medium-2 small-2 right'>
				    <p class="right">1 Hour Ago</p>
				  </div>
				  <div class='columns large-2 medium-2'>
				    <a href="jobs/companyprofile">Account Control Technology Inc.</a>
				  </div><!--close column-->
				  <div class='columns large-2 medium-2'>
				    <p>Atlanta, Georgia</p>
				  </div>

				  <div class="columns large-12 hide-for-small-only">
				    <p class="">Full-Time | Entry Level | $10/hr | Our client, a leader in the production of medical technology solutions has an immediate need for...</p>
				  </div>

				  
				</div>
				</div>
			</div>
		</div><!--close columns-->

	  <div class="columns large-4">
	  	<div class="gs-panel">
				<div class="gs-panel-header">
	    	  <h3>Job Snapshot</h3>
	   		</div>
				<div class="gs-panel-body">
		      <dl class="snapshot-list-thin">
						<dt>Employement Type</dt>
						<dd>Full-Time</dd>
						<dt>Job Type</dt>
						<dd>Management</dd>
						<dt>Education</dt>
						<dd>Not Specified</dd>
						<dt>Experience</dt>
						<dd>At least 5 year(s)</dd>
						<dt>Manages Others</dt>
						<dd>Yes</dd>
						<dt>Industry</dt>
						<dd>Construction</dd>
						<dt>Required Travel</dt>
						<dd>Not Specified</dd>
			    </dl>

 
		    </div><!--Closure of panel-body-->
	    </div><!--Closure of panel-->

 
	  </div><!--close columns-->

	</div><!--close row-->
 
</div>

app/views/jobs_matrix/jdp.html 2.erb
<!--search results navigation-->
<div class="show-for-medium-up">
    <%= render 'nextjob' %>
</div>

<div class="row">
    <div class="small-12 columns show-for-small-only">
        <a href="../jobs"> < Back</a>
    </div><!--close columns-->
</div>


    <!--ad-->
    <% if params[:branding] == "nonbranded" %>
        <div class="row">
        <%= render 'jdp_ad' %>
        </div>
    <% end %>

    <!--branding-->
    <div id="fluid" class="row">
        <%= render 'top_banner' %>
    </div>

<!--job header-->
<%= render 'job_header' %>


<div class="row">
    <!--icon bar job snapshot-->
    <div class="show-for-medium-up">
        <div class="icon-bar four-up">
          <div class="item">
            <i class="fa fa-2x fa-building-o"></i>
            <label>Full-Time</label>
          </div>
          <div class="item">
            <i class="fa fa-2x fa-calendar-o"></i>
            <label>4 Years Experience</label>
          </div>
          <div class="item">
           <i class="fa fa-2x fa-usd"></i>
            <label>$100K-$120K Salary</label>
          </div>
            <a class="item moresnapshot">
            <label>More Details</label>
          </a>
        </div>
    </div>

    <div class="small-12 columns panel show-for-small-only">
        <ul class="snapshotlist smallsnapshot">
          <li>Full-Time</li>
          <li>4 Years Experience</li>
          <li>Bachelors Degree</li>
          <li>$100K-$120K Salary</li>
          <li>Required Travel: 25%</li>
          <li>Manages Others: Yes</li>
            <li>Job Type: Information Technology</li>
            <li>No Relocation</li>
            <li>Industry: Computer Hardware, Computer Software</li>
            <li>Job ID: BHJOB2052_9418</li>
        </ul>
    </div>
</div>

<div class="row">
<!--more snapshot div-->
    <div class="small-12 medium-12 large-12 columns hidden panel" id="jobsnapshot">
        <ul class="side-nav">
            <li>Job Type: Information Technology</li>
            <li>Education: Not Specified</li>
            <li>Manages Others: Yes</li>
            <li>Relocation: No</li>
            <li>Industry: Computer Hardware, Computer Software</li>
            <li>Required Travel: Yes</li>
            <li>Job ID: BHJOB2052_9418</li>
            <a class="lesssnapshot">Hide Details</a>
        </ul>
    </div><!--close job snapshot-->
</div><!--close row-->

<div id ="row"  class="row">

    <div class="small-12 medium-12 large-8 columns">
        <h3> Job Description </h3>
        <p>SALES REPS NEEDED - B2B - OUTSIDE SALES - BUSINESS DEVELOPMENT MANAGERS 
            <br /><br />
            We are currently looking for outside sales representatives and account executives who have a background in outside sales, B2B, and business development.  If you are in sales and are confident in your sales abilities, then this opportunity may be for you.  We are looking for energetic sales reps and account executives with 5+ years of B2B outside sales and business development experience who would like an opportunity as an Outside Sales Rep with our company.
            <br /><br />
            SMS is the largest full-service business development firm serving small to mid-sized businesses in the US. Through the coordinated efforts of our corporate headquarters and field service personnel; SMS installs proven methods, systems, controls and incentives to enable business owners and their managers to maintain positive cash flow, control costs, and accelerate the growth of their companies.
            SMS is currently seeking passionate, positive, driven outside sales professionals to sell into small & medium size company business owners, presidents and CEO’s.  As an outside sales rep, you will be working as a business development manager selling B2B.  You will hold a pivotal role in helping people achieve their dreams.    
            <br /><br />
            SALES REPS - B2B - OUTSIDE SALES - BUSINESS DEVELOPMENT MANAGERS
            <br /><br />
            Responsibilities for the Outside Sales Rep - B2B - Business Development Manager - Account Executive position are as follows:
            <br /><br />
            Preparing for appointments received from assistant the day prior--all travel is local and typically within a 50 mile radius of your home
            Directing 3-4 sales leads daily with owners of small to medium sized businesses with the goal of marketing and securing Business Analysts a Survey Agreement.
            Conducting our innovative hybrid approach to qualifying potential business for new sales leads in between appointments and during networking opportunities
            Contacting Business Coordinator with feedback from appointments and sharing new business lead opportunities.
            Reviewing the day’s successes and challenges with your Sales Manager, gaining sales support as appropriate-- all administrative support people have a vested interest in your success
            <br /><br />
            In our organization, we offer the following to our outside sales - account executive - b2b - business development managers:
            <br /><br />
            Fantastic Benefits and Compensation Program
            $65,000-$85,000 realistic first year commissions
            Potential to earn 6 figure commissions
            Comprehensive new hire and ongoing training and development
            Protected territory and pre-set appointments
        </p>
        <h3>Job Requirements</h3>
        <p>SALES REPS NEEDED - B2B - OUTSIDE SALES - BUSINESS DEVELOPMENT MANAGERS
            <br /><br />
            Requirements for the Outside Sales Rep - B2B - Business Development Manager - Account Executive position are as follows: 
            <br /><br />
            At least three years of business ownership experience and/or three years of face-to-face direct sales, outside sales, B2B, Business Development experience
            Bachelor’s degree preferred but not necessary. We will consider the right experience over a degree 
            Highly self-motivated and self-disciplined with ability to work effectively with little or no supervision
            Outgoing personality with expertise at developing relationships, particularly with business owners, presidents and CEO’s
            Good communicator—excellent listening skills and ability to uncover the real “pain" a client might be experiencing
            Ability to begin work immediately
            <br /><br />
            To schedule an interview
            Call Ms. Durham 1-877-274-0147
            <br /><br />
            Or forward resume
            <br /><br />
            Keywords: Sales, salesperson, sales representative, account manager, account management, business to business sales, outside sales, B2B, business development manager, account executive, senior account executive, major account executive, national sales, national account executive, business development representative, business, general business, small business, entrepreneur, business owner, consulting
        </p>
        <h3>Equal Opportunity Employment</h3>
        <p>ABC is commited to having our online application process accesible by all, including those individuals wiht a disability where appropriate, by offering an alternative way to apply for job openings. The alternative method is only available for those who cannot otherwise complete the online applicaiton due to disability or need for accomidations. ABC provides reasonable accomidation for applicants under the guidance of the Americans with Disabilities Act (ADA), Section 503 of the Rehabilitations Act of 1973, the Vietnam-Era Veterans' Readjustment Assistance Act of 1974 and certain state and/or local laws.</p>
    </div><!--close columns-->

    <div class="small-12 medium-12 large-4 columns">
        <h3>Company Overview</h3>
        <ul>
            <li>10,000-25,000 employees</li>
            <li>www.abccompany.com</li>
        </ul>

        <p class="hide-for-small-only">
            SMS focuses on marketing strategies, strategic planning and business development. SMS, and the companies it represents, works to increase the sales, improve productivity, increase profitability, and improve the ease of operations of small- to medium-sized companies, while helping business owners reach their maximum potential and secure their financial future. 
            <br /><br />
            SMS has been instrumental in helping companies recapture lost revenue and profits from the most recent economic downturn by providing the appropriate business experts to our clients to put in place methods, systems, and controls to control costs, increase productivity, while maintaining a positive cash flow . Our strategies help determine unique, "out-of-the-box" ways to increase both business and profitability while helping our clients stay competitive in challenging markets.
            <a href="../jobs/companyprofile">Learn more about this company</a>
        </p>

        <!--premium video-->
        <% if params[:branding] == "premium" %>
            <%= render 'video' %>
        <% end %>

        <!--premium social media-->
        <% if params[:branding] == "premium" %>
            <%= render 'socialmedia' %>
        <% end %>

        <p><a href="../jobs" class="button secondary">View all jobs at abccompany</a></p>

        <!--similar jobs for nonbranded-->
        <% if params[:branding] == "nonbranded" %>
            <%= render 'similar_jobs' %>
        <% end %>
    </div><!--close columns-->

</div><!--close row-->


<!--apply button bar-->
<div class="row">
    <div class="left small-12 medium-3 large-2 columns">
            <%= link_to "Apply Now", apply_path, class: "button expand" %>
    </div><!--close button bar columns-->
    <div class="small-12 medium-3 large-3 columns">
            <a href="#" data-reveal-id="TNModal" class="button secondary expand">Join Our Talent Network</a>
            <div id="TNModal" class="reveal-modal" data-reveal>
              <h2>Talent Network Join Form</h2>
              <p>This is a placeholder for the Talent Network Join Form</p>
              <a class="close-reveal-modal">&#215;</a>
            </div>
    </div><!--close button bar columns-->
    <div class="small-12 medium-9 large-2 columns">
        <a id="report-job-link">Report Job</a>
    </div>
        <div class="hidden" id="jobreport">
            <div class="small-12 medium-8 large-8 columns">
            <p>Please help us monitor our job postings by providing us feedback on this job. If you feel this job is miscategorized or some type of spam please let us know. Once a job has been reported to us, we will investigate it further and make the appropriate adjustments. If you require a response please submit your question or concern to our <a href="#">Trust and Site Security Team</a>.</p>
                <label>Select a Report Type:
                <select>
                    <option>Fee or Investment Required</option>
                    <option>Cannot Apply/Broken Link</option>
                    <option>Possible Scam</option>
                    <option>Multiple Positions in one posting</option>
                    <option>Miscategorized</option>
                    <option>Company not identified</option>
                    <option>Irrelevant keywords</option>
                    <option>Offensive Content</option>
                    <option>Other</option>
                </select>
                </label>
                <label>Comments
                <textarea placeholder=""></textarea>
                </label>
                <a id="job-report-submit" class="button small">Submit</a>
                <a id="job-report-cancel" class="button secondary small">Cancel</a>
            </div>
        </div>
</div><!--close row-->

<div class="row hide-for-small-only">
<!--branding-->
    <% if params[:branding] == "premium" %>
        <%= render 'bottom_banner' %>
    <% end %>
</div><!--close row-->

<!--search results navigation-->
<%= render 'nextjob' %>

<div class="row">
        <div class="show-for-medium-up panel large-12 columns">
        <h3>Careerbuilder Tip</h3>
        <p>For your <a href="#">privacy and protection</a>, when applying to a job online, never give your social security number to a prospective employer, provide credit card or bank account information, or perform any sort of monetary transaction. <a href="#">Learn more</a>.
        <br /><br />
        By applying to a job using CareerBuilder.com you are agreeing to comply with and be subject to the CareerBuilder.com <a href="#">Terms and Conditions</a> for use of our website. To use our website, you must agree with the <a href="#">Terms and Conditions</a> and both meet and comply with their provisions.
        </div><!--close show for medium up-->
</div><!--close row-->