config/routes.rb
Rails.application.routes.draw do
  
  get 'jobs_matrix/index'
  get 'jobs_matrix/jdp'
  get 'jobs_matrix/aggregator'

  get 'jdp/index'

  root 'home#index'

  get 'account' => 'account#index'
  get 'apply' => 'apply#index'
  get 'jobs_matrix' => 'jobs_matrix#index'

  get 'jobs' => 'jobs#index'
  get 'jobs/job_collapse' => 'jobs#job_collapse'
  get 'jobs/jdp' => 'jobs#jdp'
  get 'jobs/job_emailed_jdp' => 'jobs#job_emailed_jdp'
  get 'jobs/job_saved_jdp' => 'jobs#job_saved_jdp'
  get 'jobs/expired_job' => 'jobs#expired_job'
  get 'jobs/mobile_filters' => 'jobs#mobile_filters'
  get 'jobs/companyprofile' => 'jobs#companyprofile'
  get 'jobs/find_jobs_landing' => 'jobs#find_jobs_landing'
  get 'jobs/find_jobs_searchstate' => 'jobs#find_jobs_searchstate'
  get 'jobs/find_jobs_jobtitles' => 'jobs#find_jobs_jobtitles'
  get 'jobs/find_jobs_company' => 'jobs#find_jobs_company'
  get 'jobs/find_jobs_category' => 'jobs#find_jobs_category'
  get 'jobs/find_jobs_accounting' => 'jobs#find_jobs_accounting'
  get 'jobs/find_jobs_accounting_state' => 'jobs#find_jobs_accounting_state'
  get 'jobs/find_jobs_accounting_alabama_city' => 'jobs#find_jobs_accounting_alabama_city'
  get 'jobs/find_jobs_alabama' => 'jobs#find_jobs_alabama'
  get 'recommendations' => 'recommendations#index'
  get 'recommendations/similarrecs' => 'recommendations#similarrecs'
  get 'recommendations/resumerecs' => 'recommendations#resumerecs'
  get 'recprefs' => 'recommendations#recprefs'
  get 'recprefs_addlocation' => 'recommendations#recprefs_addlocation'
  get 'recprefs_addskills' => 'recommendations#recprefs_addskills'
  get 'recprefs_addtitle' => 'recommendations#recprefs_addtitle'
  get 'resumes' => 'resumes#index'
  get 'resumes/post' => 'resumes#post'
  get 'resumes/preview' => 'resumes#resume_preview'
  get 'resumes/cover_letter' => 'resumes#cover_letter'
  get 'resumes/resume_selected' => 'resumes#resume_selected'
  get 'resumes/cover_letter_blank' => 'resumes#cover_letter_blank'
  get 'saved_jobs' => 'saved_jobs#index'
  get 'saved_searches' => 'saved_searches#index'
  get 'sink' => 'sink#index'
  get 'sign_in' => 'user#sign_in'
  get 'sign_up' => 'user#sign_up'
  get 'jobs/after_apply' => 'jobs#after_apply'
  get 'jobs/job_emailed' => 'jobs#job_emailed'
  get 'jobs/job_saved' => 'jobs#job_saved'
  get 'dashboard' => 'home#dashboard'
  
  get 'home-one' => 'home#experiment-1'
  get 'home-two' => 'home#experiment-2'
  get 'home-three' => 'home#experiment-3'
  get 'home-four' => 'home#experiment-4'

  get 'info' => 'info#index'

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :debug
	def index
	end

	def sign_up
	end

	private
	def debug
  	if params[:action] == "index"
  		@statuses = nil
  	end
  end
end

app/views/user/_email_field.html.erb
<label>Email
  <input type="email" <%= required %> />
  <small class="error">A valid email address is required</small>
</label>

app/views/user/_password_creation_field.html.erb
<div class="column small-12">
	<%= render 'user/password_field', password_id: "new-password", password_label: password_create_label , show_hide_id: "showhidecreation", data_abide_validator: "passwordcb"%>
</div>
<div class="column small-6 large-6 medium-6">
	<li id="character-count"> <small> 8 to 15 characters</small></li>
	<li id="lowercase-count"> <small>Lowercase Letters</small></li>
</div>
<div class="column small-6 large-6 medium-6">
	<li id="number-or-symbol"> <small>Number or Symbol</small></li>
	<li id="uppercase-count"> <small>Uppercase Letters</small></li>
</div>

app/views/user/_password_field.html.erb
<label><%= password_label %>
	<div class="row collapse">
		<div class="column small-9">
			<!-- TODO password validation -->
	    <input type="password" name="password" id=<%= password_id %> data-abide-validator=<%=data_abide_validator %> />
	    <small class="error">A valid password is required</small>
	    <!-- <small class="error">This Password doesn't work</small> -->
	  </div>
    <div class="small-3 columns">
      <a id=<%= show_hide_id %> class="button secondary postfix" onclick="$('#<%= password_id %>').togglePassword();toggle_password_text('<%= show_hide_id %>')"><i class="fa fa-eye"></i> Show</a>
    </div>
  </div>
</label>

app/views/user/_sign_in_form.html.erb
<% @search_bar = "no-search" %>
<% @footer_bar = "no-footer" %>
<div class="row"> 
	<div class="column small-12 text-center">
		<img src="http://www.placehold.it/300x90&textcareerbuilder"/>
	</div>
</div>
<div class="row">
	<%= form_tag( @path, method: "get", id: "sign-in-form") do %>
		<%= hidden_field_tag 'auth', 'authenticated' %>
		<div class="column small-12 medium-4 large-4 medium-offset-2">
			<div class="row">
				<div class="column small-12 large-centered medium-centered">
					<!-- Email Field -->
					<%= render 'user/email_field', required: "" %>
				  <!-- Ends Email-->
				</div>
			</div>
			<div class="row">
				<div class="column small-12 large-centered mshow_hide_id: "showhidecreation"edium-centered">
					<%= render 'user/password_field', show_hide_id: "showhide", password_id: "password", password_label: "password", data_abide_validator: "" %>
				</div>
			</div>
			<div class="row">
				<div class="column small-6">
		      <input id="checkbox1" type="checkbox">
		      <label for="checkbox1">Remember Me</label>
				</div>
				<div class="column small-6 end text-right">
					<a href="#" data-reveal-id="myModal">Forgot Password</a>
				</div>
			</div>
			<div class="row">
				<div class="column small-12 large-centered medium-centered">
					<%= submit_tag "Sign In", class: "button expand" %>
				</div>
			</div>
			<% if @create_or_post == nil || @create_or_post == "create" %>
				<div class="row">
					<div class="column small-12 large-centered medium-centered text-center">
						<p> Don't have an account? <%= link_to "Sign Up Now", sign_up_path %></p>
					</div>
				</div>
			<% elsif @create_or_post == "post" %>
				<div class="row">
					<div class="column small-12 large-centered medium-centered text-center">
						<p> If you don't have an account we'll help you make one <%= link_to "Post and Sign Up", resumes_path(params.merge(step: "upload").except(:action, :controller, :message)) %></p>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>
	<!-- Social Stuff-->
	<div class="column small-12 medium-4 large-4 end">
		<div class="row">
			<div class="column small-12 large-centered medium-centered text-center">
				<p> or sign in with</p>
			</div>
		</div>
		<div class="row">
			<div class="column small-12 large-centered medium-centered">
				<a href="#" class="button expand secondary">
					<i class="fa fa-facebook-official"></i>
					Facebook
				</a>
				<a href="#" class="button expand secondary" >
					<i class="fa fa-google-plus-square"></i>
					Google Plus
				</a>
			</div>
		</div>	
	</div>
</div>


<div id="myModal" class="reveal-modal" data-reveal>
	<div class="row">
		<div class="small-12 columns">
			<h2>Forgot Password</h2>
			<p class="lead">Some text about what to do here.</p>
		</div>
	</div>
	<div class="row">
		<div class="small-12 columns">
			<label>Email Address
				<input type="text" placeholder="Email Address" />
			</label>
		</div>
	</div>
	<div class="row">
		<div class="column small-12">
			<a href="#" class="button expand">Send Password</a>
		</div>
	</div>
	<a class="close-reveal-modal">&#215;</a>
</div>

app/views/user/_sign_in_form_new.html.erb
<% @search_bar = "no-search" %>
<% @footer_bar = "no-footer" %>
<% @nav_bar = "no-nav" %>

<div class="row"> 
	<div class="column small-12 text-center">
		<img src="http://www.placehold.it/300x90&amp;text=careerbuilder"/>
	</div>
</div>
<div class="row" id="double-bump">
	<div class="column small-12 medium-9 medium-centered">
		<ul class="small-block-grid-1 medium-block-grid-2">
			<li>
				<%= form_tag(@path, method: "get", id: "sign-in-form") do %>
					<%= hidden_field_tag 'auth', 'authenticated' %>
					<div class="row">
						<div class="column small-12 medium-11">
							<h2>Sign In</h2>
							<div class="row">
								<div class="column small-12 large-centered medium-centered">
									<%= render 'user/email_field', required: "" %>
								</div>
							</div>
							<div class="row">
								<div class="column small-12 large-centered mshow_hide_id: "showhidecreation"edium-centered">
									<%= render 'user/password_field', show_hide_id: "showhide", password_id: "password", password_label: "password", data_abide_validator: "" %>
								</div>
							</div>
							<div class="row">
								<div class="column small-12">
									<ul class="inline-list">
										<li>
											<label for="checkbox1">
												<input id="checkbox1" type="checkbox">
												Remember Me
											</label>
										</li>
										<li class="right">
											<a href="#" data-reveal-id="myModal">Forgot Password</a>
										</li>
									</ul>
								</div>
							</div>
							<div class="row">
								<div class="column small-12 large-centered medium-centered">
									<%= submit_tag "Sign In", class: "button expand" %>
								</div>
							</div>
							<div class="row">
								<div class="column small-12">
									<ul class="stack button-group">
										<li>
											<%= link_to "#", class: "button expand secondary", onclick: "$('#sign-in-form').submit()" do %>
												<i class="fa fa-facebook-official"></i>
												Sign In with Facebook
											<% end %>
										</li>
										<li style="margin-top:10px;">
											<%= link_to "#", class: "button expand secondary", onclick: "$('#sign-in-form').submit()" do %>
												<i class="fa fa-google-plus-square"></i>
												Sign In with Google
											<% end %>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</li>
			<li>
				<div class="row">
					<div class="column small-12 medium-11 right">
						<% if @sign_up_type == nil || @sign_up_type == "create" %>
							<h2>Create Account</h2>
							<div class="row">
								<div class="column small-12">
									<p>Don't have an account?</p> 
								</div>
							</div>
							<%= render 'user/sign_up_form' %>
						<% elsif @sign_up_type == "post" %>
							<h2>Sign Up</h2>
							<div class="row">
								<div class="column small-12">
									<p>
										If you don't have an account we'll help you make one 
									</p>
									<%= link_to "Post and Sign Up", resumes_path(step: "upload"), class: "button expand" %>
								</div>
							</div>
						<% elsif @sign_up_type == "apply" %>
							<h2>Apply as Guest</h2>
							<div class="row">
								<div class="column small-12">
									<p>You will have the opportunity to create an account after applying to this job.</p>
									<%= link_to "Apply as Guest", url_for(step: "upload"), class: "button expand" %>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>


<div id="myModal" class="reveal-modal" data-reveal>
	<div class="row">
		<div class="small-12 columns">
			<h2>Forgot Password</h2>
			<p class="lead">Some text about what to do here.</p>
		</div>
	</div>
	<div class="row">
		<div class="small-12 columns">
			<label>Email Address
				<input type="text" placeholder="Email Address" />
			</label>
		</div>
	</div>
	<div class="row">
		<div class="column small-12">
			<a href="#" class="button expand">Send Password</a>
		</div>
	</div>
	<a class="close-reveal-modal">&#215;</a>
</div>

app/views/user/_sign_up_form.html.erb
<form class="custom" data-abide>
	<div class="row">
		<div class="column small-12">
			<%= render 'user/text_field', text_label: "First Name", required:"required" %>
		</div>
		<div class="column small-12">
			<%= render 'user/text_field', text_label: "Last Name", required:"required" %>
		</div>
		<div class="column small-12">
			<%= render 'user/email_field', required:"required" %>
		</div>
		<div class="column small-12">
			<%= render 'user/zip_field', required:"required" %>
		</div>
		<%= render 'user/password_creation_field', password_create_label: "Password" %>
		<div class="column small-12" id="bump">
			<%= link_to "Sign Up", root_path(auth: "authenticated"), class: "button expand" %>
		</div>

		<div class="column small-12">
			<p>By clicking Sign Up, you agree to CareerBuilder's <a href="#">User Agreement</a>, <a href="#">Privacy Policy</a> and <a href="#">Cookie Policy</a>.</p>
		</div>
	</div>
</form>


<!-- <div class="morph-button morph-button-modal morph-button-modal-1 morph-button-fixed">
				<button type="button">Terms &amp; Conditions</button>
				<div class="morph-content">
					<div>
						<div class="content-style-text">
							<span class="icon icon-close">Close the dialog</span>
							<h2>Terms &amp; Conditions</h2>
							<p>Pea horseradish azuki bean lettuce avocado asparagus okra. Kohlrabi radish okra azuki bean corn fava bean mustard tigernut juccama green bean celtuce collard greens avocado quandong <strong>fennel gumbo</strong> black-eyed pea. Grape silver beet watercress potato tigernut corn groundnut. Chickweed okra pea winter purslane coriander yarrow sweet pepper radish garlic brussels sprout groundnut summer purslane earthnut pea <strong>tomato spring onion</strong> azuki bean gourd.</p>
							<p><input id="terms" type="checkbox" /><label for="terms">I accept the terms &amp; conditions.</label></p>
						</div>
					</div>
				</div>
			</div> --><!-- morph-button -->

<script>
			(function() {	
				var docElem = window.document.documentElement, didScroll, scrollPosition;

				// trick to prevent scrolling when opening/closing button
				function noScrollFn() {
					window.scrollTo( scrollPosition ? scrollPosition.x : 0, scrollPosition ? scrollPosition.y : 0 );
				}

				function noScroll() {
					window.removeEventListener( 'scroll', scrollHandler );
					window.addEventListener( 'scroll', noScrollFn );
				}

				function scrollFn() {
					window.addEventListener( 'scroll', scrollHandler );
				}

				function canScroll() {
					window.removeEventListener( 'scroll', noScrollFn );
					scrollFn();
				}

				function scrollHandler() {
					if( !didScroll ) {
						didScroll = true;
						setTimeout( function() { scrollPage(); }, 60 );
					}
				};

				function scrollPage() {
					scrollPosition = { x : window.pageXOffset || docElem.scrollLeft, y : window.pageYOffset || docElem.scrollTop };
					didScroll = false;
				};

				scrollFn();

				var UIBtnn = new UIMorphingButton( document.querySelector( '.morph-button' ), {
					closeEl : '.icon-close',
					onBeforeOpen : function() {
						// don't allow to scroll
						noScroll();
					},
					onAfterOpen : function() {
						// can scroll again
						canScroll();
					},
					onBeforeClose : function() {
						// don't allow to scroll
						noScroll();
					},
					onAfterClose : function() {
						// can scroll again
						canScroll();
					}
				} );

				document.getElementById( 'terms' ).addEventListener( 'change', function() {
					UIBtnn.toggle();
				} );
			})();
		</script>

app/views/user/_text_field.html.erb
<label><%= text_label %>
	<input type="text" <%= required %> />
	<small class="error">This field is required</small>
</label>

app/views/user/_zip_field.html.erb
<label>Zipcode
  <input type="number" <%= required %>/>
  <small class="error">A valid zip code is required</small>
</label>

app/views/user/index.html.erb
<% @search_bar = "no-search" %>
<div class="row"> 
	<div class="column small-12 text-center">
		<img src="#"/>
	</div>

</div>
<!-- Form Area -->

<div class="row">
	<form data-abide>
		<div class="column small-12 medium-6 large-6">
			<div class="row">
				<div class="column small-12 large-centered medium-centered">
					<!-- Email Field -->
					<div class="email-field">
					    <label>Email <small>required</small>
					      <input type="email" required>
					    </label>
					    <small class="error">An email address is required.</small>
				  </div>
				  <!-- Ends Email-->
				</div>
			</div>
			<div class="row">
				<div class="column small-12 large-centered medium-centered">
					<%= render 'password_field' %>
				</div>
			</div>
			<div class="row">
				<div class="column small-6">
		      <input id="checkbox1" type="checkbox">
		      <label for="checkbox1">Remember Me</label>
				</div>
				<div class="column small-6 end text-right">
					<a href="#" data-reveal-id="myModal">Forgot Password</a>
				</div>
			</div>
			<div class="row">
				<div class="column small-12 large-centered medium-centered">
					<a href="#" class="button expand">Sign In</a>
				</div>
			</div>
			<div class="row">
				<div class="column small-12 large-centered medium-centered text-center">
					<p> Don't have an account? <%= link_to "Sign Up Now", user_sign_up_path %></p>
				</div>
			</div>
		</div>
	</form>
	<!-- Social Stuff-->
	<div class="column small-12 medium-5 large-5">
		<div class="row">
			<div class="column small-12 large-centered medium-centered text-center">
				<p> or sign in with</p>
			</div>
		</div>
		<div class="row">
			<div class="column small-12 large-centered medium-centered">
				<a href="#" class="button expand">Facebook </a>
				<a href="#" class="button expand">Google Plus </a>
			</div>
		</div>	
	</div>
</div>


<div id="myModal" class="reveal-modal" data-reveal>
	<h2>Forgot Password</h2>
	<p class="lead">Some text about what to do here.</p>
	<div class="row">
		<div class="large-12 columns">
			<label>Email Address
				<input type="text" placeholder="Email Address" />
			</label>
		</div>
	</div>
	<div class="row">
		<a href="#" class="button ">Send Password</a>
	</div>
	<a class="close-reveal-modal">&#215;</a>
</div>

app/views/user/sign_in.html.erb
<!-- Form Area -->
<% @path = root_path %>
<% @nav_bar = "no-nav" %>
<%= render 'sign_in_form_new' %>